name 'conoha'
maintainer 'Yukihiro Okada'
maintainer_email 'you@example.com'
license 'MIT'
description 'Installs/Configures conoha VPS'
long_description 'Installs/Configures conoha VPS for me'
version '0.2.0'
